apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJXV0Z1VUc5dWIyMWhjbVYyVFZBNloyaHdYMnR5V20xT1MyMDJTR05PTTJkd1ZESklaMWxFWlc1V1lWWXpSbWRWZURKV1ZuVTJiUT09IgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
