{{- if .Values.proxyService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.proxyService.replicas }}
  selector:
    matchLabels:
      app: proxy-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      containers:
      - name: proxy-service
        image: {{ .Values.proxyService.image.repository }}:{{ .Values.proxyService.image.tag }}
        imagePullPolicy: {{ .Values.proxyService.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.proxyService.service.targetPort }}
        env:
        - name: {{ .Values.proxyService.env.proxy.name }}
          value: "{{ .Values.proxyService.env.proxy.value }}"
        - name: {{ .Values.proxyService.env.monolith.name }}
          value: "{{ .Values.proxyService.env.monolith.value }}"
        - name: {{ .Values.proxyService.env.movies.name }}
          value: "{{ .Values.proxyService.env.movies.value }}"
        - name: {{ .Values.proxyService.env.events.name }}
          value: "{{ .Values.proxyService.env.events.value }}"
        - name: GRADUAL_MIGRATION
          value: "{{ .Values.proxyService.env.gradual_migration }}"
        - name: MOVIES_MIGRATION_PERCENT
          value: "{{ .Values.proxyService.env.movies_migration_percent }}"
        envFrom:
        - configMapRef:
            name: cinemaabyss-config
        - secretRef:
            name: cinemaabyss-secrets
        resources:
          limits:
            cpu: {{ .Values.proxyService.resources.limits.cpu }}
            memory: {{ .Values.proxyService.resources.limits.memory }}
          requests:
            cpu: {{ .Values.proxyService.resources.requests.cpu }}
            memory: {{ .Values.proxyService.resources.requests.memory }}
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: proxy-service
  ports:
  - port: {{ .Values.proxyService.service.port }}
    targetPort: {{ .Values.proxyService.service.targetPort }}
  type: {{ .Values.proxyService.service.type }}
{{- end }}